export type { FileAccessDecision, PreToolDecision, ToolCall } from './types'
export { canonicalizePath, isFullyQualifiedPath, isInsidePath, stripDevicePrefix } from './canonical'
export { classifyRelPath, gateFileAccess, resolveInsideBook, toPosixRel } from './paths'
export { decidePreExecute, extractToolPath, isMutatingFileTool } from './preExecute'
export { gateWriteDraft, isDraftRelPath, parseDraftChapterKey, reportDraftReadiness, type DraftReadiness } from './writeDraft'
